#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                                                                       ##
##                  Language Technologies Institute                      ##
##                     Carnegie Mellon University                        ##
##                      Copyright (c) 1998-2004                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################

LANG=C; export LANG

echo "((Relation.LTS.down.name" >ltsLTS.desc
awk '{print $1}' lex.feats | sort -u >> ltsLTS.desc
echo ') (p.p.p.p.name ignore ' >>ltsLTS.desc
awk '{print $2}' lex.feats | sort -u >> ltsLTS.desc
echo ') (p.p.p.name ' >>ltsLTS.desc
awk '{print $3}' lex.feats | sort -u >> ltsLTS.desc
echo ') (p.p.name ' >>ltsLTS.desc
awk '{print $4}' lex.feats | sort -u >> ltsLTS.desc
echo ') (p.name ' >>ltsLTS.desc
awk '{print $5}' lex.feats | sort -u >> ltsLTS.desc
echo ') (name ' >>ltsLTS.desc
awk '{print $6}' lex.feats | sort -u >> ltsLTS.desc
echo ') (n.name ' >>ltsLTS.desc
awk '{print $7}' lex.feats | sort -u >> ltsLTS.desc
echo ') (n.n.name ' >>ltsLTS.desc
awk '{print $8}' lex.feats | sort -u >> ltsLTS.desc
echo ') (n.n.n.name ' >>ltsLTS.desc
awk '{print $9}' lex.feats | sort -u >> ltsLTS.desc
echo ') (n.n.n.n.name ignore' >>ltsLTS.desc
awk '{print $10}' lex.feats | sort -u >> ltsLTS.desc
echo ') (pos ignore' >>ltsLTS.desc
awk 'BEGIN {print "n"} {print $11}' lex.feats | sort -u >> ltsLTS.desc
echo '))' >>ltsLTS.desc

for i in `awk '{print $6}' lex.feats | sort -u`
do
   # Stop value for wagon
   STOP=3

   # Find training set for letter $i
   if [ -f lex.feats.train ]
   then 
      echo letter $i STOP $STOP TRAIN SET
      cat lex.feats.train |
       awk '{if ($6 == "'$i'") print $0}' >ltsdataTRAIN.$i.feats
   else
      echo letter $i STOP $STOP ALL
      cat lex.feats |
       awk '{if ($6 == "'$i'") print $0}' >ltsdataTRAIN.$i.feats
   fi

   $ESTDIR/bin/wagon -data ltsdataTRAIN.$i.feats -test ltsdataTRAIN.$i.feats \
          -desc ltsLTS.desc -stop $STOP -output lts.$i.tree

done
