#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                     Carnegie Mellon University                        ##
##                         Copyright (c) 2012                            ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Compute the mean cepstral distortion of predicted against reference  ##
##  mceps (ccoeffs/*.mcep)                                               ##
###########################################################################

LANG=C; export LANG

if [ ! "$ESTDIR" ]
then
   echo "environment variable ESTDIR is unset"
   echo "set it to your local speech tools directory e.g."
   echo '   bash$ export ESTDIR=/home/awb/projects/speech_tools/'
   echo or
   echo '   csh% setenv ESTDIR /home/awb/projects/speech_tools/'
   exit 1
fi

if [ ! "$FESTVOXDIR" ]
then
   echo "environment variable FESTVOXDIR is unset"
   echo "set it to your local festvox directory e.g."
   echo '   bash$ export FESTVOXDIR=/home/awb/projects/festvox/'
   echo or
   echo '   csh% setenv FESTVOXDIR /home/awb/projects/festvox/'
   exit 1
fi

if [ $# = 0 ]
then
    echo "Computed the spectral distortion, assuming the standard festvox voice structure"
    echo "Usage: $FESTVOXDIR/src/clustergen/cg_get_mcd etc/txt.done.data.test test/cgp"
    exit 1
fi

tmp=/tmp/mcd$$ 
cnt=0 
scd=0 

for i in `awk '{print $2}' $1` 
do
    $ESTDIR/bin/ch_track -otype ascii $2/$i.mcep | 
      awk '{for(i=2;i<=NF;i++){printf("%s\n",$i)}}' | 
      perl $FESTVOXDIR/src/clustergen/a2d.pl > $tmp.src

    $ESTDIR/bin/ch_track -otype ascii ccoefs/$i.mcep |
      awk '{for (i=2;i<=26;i++){printf("%s\n",$i)}}' | 
      perl $FESTVOXDIR/src/clustergen/a2d.pl > $tmp.tgt

    cd=`$FESTVOXDIR/src/vc/src/dtw/dtw -nmsg -getcd -dim 25 -sdim 0 -ldim 24 $tmp.src $tmp.tgt `
    cd=`echo $cd| sed 's/.* //g'`

    scd=`echo "$scd + $cd" | bc -l`
    cnt=`echo "$cnt + 1" | bc -l`
#   echo $i" MCD:"$cd
    rm -f $tmp.src $tmp.tgt
done

mcd=`echo "$scd / $cnt"| bc -l`
echo "MCD: $mcd"
