#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                     Carnegie Mellon University                        ##
##                         Copyright (c) 2005                            ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Resynth a track file into a waveform file                            ##
##  will be embedded in festival at some point                           ##
##                                                                       ##
###########################################################################

LANG=C; export LANG

TRACK=$1
WAVEFORM=$2

TMPFILENAME=/tmp/cg_$$
F0FILENAME=$TMPFILENAME.f0
NPOWFILENAME=$TMPFILENAME.npow
COEFSFILENAME=$TMPFILENAME.coefs

synthesis=$FESTVOXDIR/src/vc/src/synthesis/synthesis
ORDER=24

if [ "$CLUSTERGENDIR" = "" ]
then
    CLUSTERGENDIR=$FESTVOXDIR/src/clustergen
fi

$ESTDIR/bin/ch_track -otype ascii $TRACK |
awk '{print $1}' >$F0FILENAME

# $ESTDIR/bin/ch_track -otype ascii $TRACK |
# awk '{print $2}' |
# perl $CLUSTERGENDIR/a2d.pl >$NPOWFILENAME

$ESTDIR/bin/ch_track -otype ascii $TRACK |
awk '{for (i=2; i<=26; i++)
       printf("%s\n",$i); }' |
perl $CLUSTERGENDIR/a2d.pl >$COEFSFILENAME

#$synthesis -order $ORDER $F0FILENAME $COEFSFILENAME $WAVEFORM  >/dev/null 2>&1
$synthesis -order $ORDER $F0FILENAME $COEFSFILENAME $WAVEFORM 

rm -f $F0FILENAME $COEFSFILENAME



