#!/bin/sh
####################################################-*-mode:shell-script-*-
##                                                                       ##
##                     Carnegie Mellon University                        ##
##                        Copyright (c) 2008                             ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##  Make voicing files by a number of different methods depending on     ##
##  user choice                                                          ##
##                                                                       ##
##  ./bin/make_voices TYPE [ETC/TXT.DONE.DATA]                           ##
##                                                                       ##
##  if TYPE == pda    use $ESTDIR/bin/pda                                ##
##  if TYPE == get_f0 use $ESPS_BASE/bin/get_f0dd                        ##
##  if TYPE == tempo  use $FESTVOXDIR/src/vc/src/tempo/tempo             ##
##                                                                       ##
###########################################################################

LANG=C; export LANG

if [ $# = 0 ]
then
   echo "Extract voicing from the waveform files"
   echo "Usage:  bin/make_voicing TYPE"
   echo "Will create voicing files in v/*.v"
   exit 1
fi

if [ ! "$ESTDIR" ]
then
   echo "environment variable ESTDIR is unset"
   echo "set it to your local speech tools directory e.g."
   echo '   bash$ export ESTDIR=/home/awb/projects/speech_tools/'
   echo or
   echo '   csh% setenv ESTDIR /home/awb/projects/speech_tools/'
   exit 1
fi

TEMPO=$FESTVOXDIR/src/vc/src/tempo/tempo

F0MIN=80
F0MAX=250
F0MEAN=150
if [ -f etc/f0.params ]
then
   . etc/f0.params
fi

if [ "$PROMPTFILE" = "" ]
then
   if [ $# = 2 ]
   then
      PROMPTFILE=$2
   else
      PROMPTFILE=etc/txt.done.data
   fi
fi

if [ ! -d v ]
then
   mkdir v
fi

if [ $1 = "pda" ]
then
   cat $PROMPTFILE |
   awk '{print $2}' |
   while read fname
   do
     echo $fname voicing pda
     $ESTDIR/bin/pda wav/$fname.wav |
     awk '{if ($1 > 0) print 1; else print 0}' >v/$fname.v
   done

   exit 0
fi

if [ $1 = "get_f0" ]
then

   cat $PROMPTFILE |
   awk '{print $2}' |
   while read fname
   do
     echo $fname voicing get_f0
     $ESPS_BASE/bin/get_f0 -i 0.005 wav/$fname.wav v/$fname.gf
     ch_track -otype ascii v/$fname.gf |
     awk '{if ($2 < 1) print 0; else print 1}' >v/$fname.v
     rm -rf v/$fname.gf
   done

   exit 0
fi

if [ $1 = "tempo" ]
then

   cat $PROMPTFILE |
   awk '{print $2}' |
   while read fname
   do
     echo $fname voicing tempo
     $TEMPO -nmsg -maxf0 $F0MAX -minf0 $F0MIN wav/$fname.wav v/$fname.tp
     cat v/$fname.tp |
     awk '{if ($1 > 0) print 1; else print 0}' >v/$fname.v
     rm -rf v/$fname.tp
   done

   exit 0
fi



