#!/bin/sh
###########################################################################
##                                                                       ##
##                   Carnegie Mellon University and                      ##
##                   Alan W Black and Kevin A. Lenzo                     ##
##                      Copyright (c) 1998-2000                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  *If* we lived in a perfect world this script would build the whole   ##
##  limited domain synthesis voice.  But it should just be looked at as  ##
##  the list of process you want to go through, run each by hand rather  ##
##  then as a single script                                              ##
##                                                                       ##
###########################################################################

LANG=C; export LANG

if [ $# = 1 ]
then
   LDOM=$1
else
   # Time is the canonical example
   LDOM=time
fi

## Build initial directories and copy basic files
$FESTVOXDIR/src/ldom/setup_ldom $LDOM

## Build prompts
festival -b etc/ldom.scm "(build_prompts \""etc/$LDOM".data\")"

## Record prompts
#bin/prompt_them etc/$LDOM.data
# awb debugging: this simply copies existing (synthesized) examples
cp -p ../tel-wav/*.wav wav/

## Label prompts
bin/make_labs prompt-wav/*.wav

## Check the labels (if you care)
# emulabel etc/emu_lab

## Make utterances from prompts
festival -b etc/ldom.scm "(build_utts \""etc/$LDOM".data\")"

## Get pitch marks and MFCC
bin/make_pm_wave wav/*.wav
bin/make_mcep wav/*.wav

## Make the cluster models
festival -b festvox/$LDOM"_build.scm" "(do_all)"

