#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                   Carnegie Mellon University and                      ##
##                   Alan W Black and Kevin A. Lenzo                     ##
##                      Copyright (c) 1998-2000                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
###                                                                       ##
###  Generate (filled) pitchmark file from EGG/LAR files                  ##
###                                                                       ##
############################################################################

LANG=C; export LANG

if [ $# = 0 ]
then
   echo "Extract pitchmarks from EGG signals"
   echo "Usage:  bin/make_pm lar/*.lar"
   echo "Will create pm/*.pm"
   echo "pitchmark parameters are set for male speaker, edit for female."
   exit 1
fi

if [ ! "$ESTDIR" ]
then
   echo "environment variable ESTDIR is unset"
   echo "set it to your local speech tools directory e.g."
   echo '   bash$ export ESTDIR=/home/awb/projects/speech_tools/'
   echo or
   echo '   csh% setenv ESTDIR /home/awb/projects/speech_tools/'
   exit 1
fi

for i in $*
do
   fname=`basename $i .lar`
   echo $i PM
   # Due to a bug this only works for 16Khz
   $ESTDIR/bin/ch_wave $i -F 16000 -o tmp$$.lar
   # You'll need -inv if you are at CMU (or CSTR and maybe elsewhere)
   # Male
   $ESTDIR/bin/pitchmark tmp$$.lar -inv -o pm/$fname.pm -otype est -min 0.005 -max 0.012 -fill -def 0.01 -wave_end
   # Female
#   $ESTDIR/bin/pitchmark tmp$$.lar -inv -o pm/$fname.pm -otype est -min 0.00333 -max 0.0075 -fill -def 0.006 -wave_end
   rm -f tmp$$.lar
done
