#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                   Carnegie Mellon University and                      ##
##                   Alan W Black and Kevin A. Lenzo                     ##
##                      Copyright (c) 1998-2000                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Generate xlabel format representation of EST pm files suitable       ##
##  for view in University of Macquarie's emulabel or Entropic's Xwaves  ##
##                                                                       ##
###########################################################################

LANG=C; export LANG

if [ $# = 0 ]
then
   echo "Make pm labels for viewing in emulabel or similar"
   echo "Usage:  bin/make_pmlab_pm pm/*.pm"
   echo "Will create pm_lab/*.lab"
   exit 1
fi

if [ `dirname $1` = "pm_lab" ]
then
   echo 
   echo "ERROR"
   echo "This function generates pmlab from pm files.  "
   echo "you probably wanted to type "
   echo "      bin/make_pmlab_pm pm/*.pm"
   echo "not"
   echo "      bin/make_pmlab_pm pm_lab/*.lab"
   echo
   exit
fi

for i in $* 
do
   echo $i
   fname=`basename $i .pm`
   awk '{if ($1 == "EST_Header_End")
         {
            post_header = 1;
            printf("#\n");
         }
         else if (post_header == 1)
         {
	     printf("%f 125 %f\n",$1,$2);
         }}' $i >pm_lab/$fname.lab
done
