#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                   Carnegie Mellon University and                      ##
##                   Alan W Black and Kevin A. Lenzo                     ##
##                      Copyright (c) 1998-2000                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Make the directories assumes . is the db directory                   ##
##                                                                       ##
###########################################################################

##
##  This makes more directories than you may need
##

LANG=C; export LANG

mkdir bin
mkdir wav
mkdir recording
mkdir lab
mkdir lar
mkdir lpc
mkdir mcep
mkdir pm
mkdir pm_lab
mkdir wrd
mkdir syl
mkdir phr
mkdir f0
mkdir etc
mkdir group
mkdir festival
mkdir festival/utts
mkdir festival/coeffs
mkdir festival/f0
mkdir festival/disttabs
mkdir festival/trees
mkdir festival/feats
mkdir festival/clunits
mkdir festival/phrbrk
mkdir festival/dur
mkdir emu
mkdir emu/lab_hlb
mkdir emu/pm_hlb
mkdir scratch
mkdir scratch/wav
mkdir scratch/lab
mkdir festvox
mkdir versions
mkdir prompt-wav
mkdir prompt-lab
mkdir prompt-cep
mkdir prompt-utt
mkdir cep
